package com.timeface.model.baseRes;

public class FixedAssetInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.fa_no
     *
     * @mbggenerated
     */
    private String faNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.descri
     *
     * @mbggenerated
     */
    private String descri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.supply_channel
     *
     * @mbggenerated
     */
    private String supplyChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.supplier
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.storage_member
     *
     * @mbggenerated
     */
    private Long storageMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_fixed_assets_info.confirm_member
     *
     * @mbggenerated
     */
    private Long confirmMember;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.id
     *
     * @return the value of oa_fixed_assets_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.id
     *
     * @param id the value for oa_fixed_assets_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.category_id
     *
     * @return the value of oa_fixed_assets_info.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.category_id
     *
     * @param categoryId the value for oa_fixed_assets_info.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.fa_no
     *
     * @return the value of oa_fixed_assets_info.fa_no
     *
     * @mbggenerated
     */
    public String getFaNo() {
        return faNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.fa_no
     *
     * @param faNo the value for oa_fixed_assets_info.fa_no
     *
     * @mbggenerated
     */
    public void setFaNo(String faNo) {
        this.faNo = faNo == null ? null : faNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.name
     *
     * @return the value of oa_fixed_assets_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.name
     *
     * @param name the value for oa_fixed_assets_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.descri
     *
     * @return the value of oa_fixed_assets_info.descri
     *
     * @mbggenerated
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.descri
     *
     * @param descri the value for oa_fixed_assets_info.descri
     *
     * @mbggenerated
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.price
     *
     * @return the value of oa_fixed_assets_info.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.price
     *
     * @param price the value for oa_fixed_assets_info.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.num
     *
     * @return the value of oa_fixed_assets_info.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.num
     *
     * @param num the value for oa_fixed_assets_info.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.supply_channel
     *
     * @return the value of oa_fixed_assets_info.supply_channel
     *
     * @mbggenerated
     */
    public String getSupplyChannel() {
        return supplyChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.supply_channel
     *
     * @param supplyChannel the value for oa_fixed_assets_info.supply_channel
     *
     * @mbggenerated
     */
    public void setSupplyChannel(String supplyChannel) {
        this.supplyChannel = supplyChannel == null ? null : supplyChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.supplier
     *
     * @return the value of oa_fixed_assets_info.supplier
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.supplier
     *
     * @param supplier the value for oa_fixed_assets_info.supplier
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.status
     *
     * @return the value of oa_fixed_assets_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.status
     *
     * @param status the value for oa_fixed_assets_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.storage_member
     *
     * @return the value of oa_fixed_assets_info.storage_member
     *
     * @mbggenerated
     */
    public Long getStorageMember() {
        return storageMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.storage_member
     *
     * @param storageMember the value for oa_fixed_assets_info.storage_member
     *
     * @mbggenerated
     */
    public void setStorageMember(Long storageMember) {
        this.storageMember = storageMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_fixed_assets_info.confirm_member
     *
     * @return the value of oa_fixed_assets_info.confirm_member
     *
     * @mbggenerated
     */
    public Long getConfirmMember() {
        return confirmMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_fixed_assets_info.confirm_member
     *
     * @param confirmMember the value for oa_fixed_assets_info.confirm_member
     *
     * @mbggenerated
     */
    public void setConfirmMember(Long confirmMember) {
        this.confirmMember = confirmMember;
    }
}