package com.timeface.mapper.baseRes;


import com.timeface.model.baseRes.FixedAssetInfo;

public interface FixedAssetInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    int insert(FixedAssetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    int insertSelective(FixedAssetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    FixedAssetInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FixedAssetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_fixed_assets_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FixedAssetInfo record);
}